import Footer from '@/component/Footer/Footer';
import Header from '@/component/Header/Header';
// import localFont from 'next/font/local';
import { KoHo } from 'next/font/google';
import './globals.scss';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

const koHo = KoHo({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={koHo.className}>
        {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
